### PR TITLE
Add 'Pause All Devices' / 'Resume All Devices' and 'Rescan All' menu items

### PR DESCRIPTION
**Pull request by virusman**
also, refactor API calls

### CODE REVIEW

**Comment by xor-gate** [comment]
Thanks for your cleanup, no comments!

**Comment by xor-gate** [comment]
@virusman would you like to create and sign new release, I have also update the bundle to use latest syncthing v0.14.46? If all is fine I will update the appcast.xml with release notes and a notice we have changed to use your signing keys.

**Comment by xor-gate** [comment]
I'm unable to find it, could you supply a link ?

**Comment by virusman** [comment]
https://github.com/xor-gate/syncthing-macosx/releases/tag/untagged-5e67af2fc70e598bcb63

**Comment by xor-gate** [comment]
Thanks victor it works like a charm!

screen shot 2018-04-19 at 21 38 59

**Pull request merged**
