### PR TITLE
fixed homebrew typo

### PR DESCRIPTION
**Pull request by kmutahar**
Fixed homebrew cask command since it has been renamed to remove "app" suffix per issue https://github.com/Homebrew/homebrew-cask/commit/f2990ac0379ef538627e598f20644d73557a06fe

### CODE REVIEW

**Comment by xor-gate** [comment]
Sorry for the late reply, the README has changed somewhat would you like to add it as a note with correct link as it is not mentioned anymore. Or should we close this? IMHO it would be better to add it when using the wrapper the homebrew version should not be installed. Let me know what you think (changed readme) or closing the PR. Thanks!

**Comment by kmutahar** [comment]
@xor-gate Sorry for the delay, I have fixed it and included the homebrew version. its worded in a way that you can install it using the github release or using homebrew. and a notice is already at the top so its clear.

**Comment by xor-gate** [comment]
ping @calmh it seems the Release DMG build fails in TeamCity, could you have a look?

**Comment by xor-gate** [comment]
Thanks @kmutahar !

**Comment by calmh** [comment]
I don't see more than you do, unfortunately. Some script execution deep in the xcode build is failing.

**Comment by calmh** [comment]
I have now deployed a brand new builder with Mojave and latest Xcode, and the build passes. 🤷‍♂

**Comment by xor-gate** [comment]
> I have now deployed a brand new builder with Mojave and latest Xcode, and the build passes. 🤷‍♂

Awesome, its a shame the Debug build passed.

**Pull request merged**
