### PR TITLE
Add appcast.xml generation action

### PR DESCRIPTION
**Pull request by calmh**
This adds an action to generate the appcast.xml and push it to cloud storage bucket. This replaces the thing currently running on build.syncthing.net, which is in a slow death spiral.

I set the action to run nightly and manually; since it's based on the published releases it should be fine to run periodically (generating identical contents each time) and manually in case a quick update is required.

(Also refreshed the dependencies for the generation script while I was in there.)

The result is currently at https://syncthing-macos.ams3.digitaloceanspaces.com/appcast/appcast.xml, and I'll update the upgrades.syncthing.net proxy to point there once merged.

### CODE REVIEW

**Review by xor-gate — APPROVED** [review]

**Comment by xor-gate** [comment]
LGTM

**Comment by xor-gate** [comment]
Seems to work (manual triggered) https://github.com/syncthing/syncthing-macos/actions/runs/6408575114

**Comment by xor-gate** [comment]
@calmh seems https://upgrades.syncthing.net/syncthing-macos/appcast.xml doesn't proxy to https://ams3.digitaloceanspaces.com/syncthing-macos/appcast/appcast.xml. Have you updated the proxy config?

**Comment by calmh** [comment]
Nope, I didn't, but now I did! :)

**Comment by xor-gate** [comment]
Thanks Jakob!

**Pull request merged**
