### PR TITLE
Preferences window reworked with toolbar

### PR DESCRIPTION
**Pull request by xor-gate**

### CODE REVIEW

**Comment by virusman** [comment]
The new release doesn't start syntching anymore for me.

**Comment by virusman** [comment]
Found the cause:     //[_syncthing runExecutable]; in STApplication, looks like leftover debug change :)

**Comment by xor-gate** [comment]
Thats a oops! I will release a new one today :+)

**Comment by xor-gate** [comment]
@virusman done!

https://github.com/xor-gate/syncthing-macosx/releases/tag/v0.14.8-1

**Pull request merged**
