### PR TITLE
Use cocoapods for dependency management

### PR DESCRIPTION
**Pull request by xor-gate**
Implements #57

### CODE REVIEW

**Comment by xor-gate** [comment]
@virusman i'm going to merge myself as I would like to make some progress. If you don't have time to contribute to the project it is no problem, just let me know I don't have to assign you and wait.

**Comment by virusman** [comment]
@xor-gate Oh sorry, I missed those :( Sorry for keeping you waiting.
Is it possible to remove Pods folder? I think the most common approach is to not check it in, but ask devs to run pod install before opening the project, so you don’t have to keep 3rd party code in the repo.

**Comment by xor-gate** [comment]
Aah not a problem, I didn't know we should not commit the Pods folder. But when are offline or the depencency goes away and somebody doesn't have a copy we can be in real trouble. Or is this intended?

**Comment by virusman** [comment]
Once you do pod install, it works. Since you need to be online to clone this repository in the first place, I guess the requirement to do pod install shouldn’t be a big deal..

**Comment by virusman** [comment]
Also, one would have to run pod install after pulling changes from master if the dependencies were changed.

**Comment by xor-gate** [comment]
Yes thats true, maybe I should create also a dist script for sourcecode including vendored dependencies per-release.

**Comment by xor-gate** [comment]
Maybe i'm to paranoid to leave the application and its Pods together and update on-demand. Just like the go `vendor` folder "pins" the dependencies and the tooling updates it on-demand. 

Cons:
* Large VCS repository size.
* VCS history littered with vendored package updates.
* A goal of one repository per project. Keep the separation clean.

Pros
 * Anyone who grabs the repo has everything needed to build the application.
 * CI/CD systems can run more quickly when it doesn't have to get any dependencies.
 * The entire application and it's dependencies are in one place.
 * When some freak decides to take the dependency offline from the global CocoaPods registry we still have a copy

Source: https://codeengineered.com/blog/2015/go-should-i-vendor/

**Comment by xor-gate** [comment]
Searched the docs and found this https://guides.cocoapods.org/using/pod-install-vs-update.html#commit-your-podfilelock

**Comment by xor-gate** [comment]
And this https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control

**Pull request merged**
