### PR TITLE
Upgrade to Swift 4.0

### PR DESCRIPTION
**Pull request by yan12125**
Xcode 10.2 no longer support Swift 3.0

### CODE REVIEW

**Comment by yan12125** [comment]
Oh, the Travis CI builder uses Xcode 8, while Swift 4 require Xcode 9...

**Review by calmh — APPROVED** [review]

**Comment by yan12125** [comment]
@calmh Thanks for reviewing. Do you think it's OK to remove support for building on Xcode 8? (I guess built binaries will continue to work on 10.10, but I cann't try as I have only 10.14)

**Comment by calmh** [comment]
IMHO yes, and I don't particularly care about Travis, but leaving for @xor-gate to decide.

**Comment by yan12125** [comment]
Got it! Forunately, keeping tests green is easier than I've thought.

**Review by xor-gate — APPROVED** [review]

**Comment by xor-gate** [comment]
Thanks both, IMHO i would like to keep travis also intact so we have green marks or red crosses in the PRs. Thanks @yan12125 for your contribution!

**Pull request merged**
