### PR TITLE
Replace round icon with a Big Sur style icon

### PR DESCRIPTION
**Pull request by jakob**
This PR replaces the round icon with a Big Sur style squircle icon to make it look more like other modern Mac apps.

This fixes issue #153
 
All I've done is replace the icns file. I have not yet attempted to actually build the app with the new icon.

If you make a new build, I can help test it.

### CODE REVIEW

**Comment by jakob** [comment]
I checked the Release DMG from TeamCity and in my opinion it looks good on a Retina display on Monterey.

I will check it on a non-retina display tomorrow.

**Comment by jakob** [comment]
I just tried it on a non-Retina display and there's something funny going on with the 16px icon on a white background. I'm changing this to a draft PR until I fix this.

**Comment by xor-gate** [comment]
You may also create an `extra` folder in the root and place the design file there maybe name it `icon`. Thanks for your effort!

**Comment by jakob** [comment]
I re-did the icon in Sketch, and now it looks good on macOS Monterey both on Retina and non-Retina displays.

**Pull request merged**
